/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.QuanLy;

import Model.AppData;
import UI.Login;
import UI.SinhVien.*;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author vankhanh
 */
public class TrangChuQuanLy extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    public TrangChuQuanLy() {
        initComponents();
        hienThi();
        btnThoat.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int confirmed = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn thoát khỏi chương trình không?", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                if (confirmed == JOptionPane.YES_OPTION) {
                    Login login = new Login();
                    login.setLocationRelativeTo(null);
                    login.show();
                    dispose();
                }
            }
        });
    }

    private void hienThi() {
        Timer timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss dd/MM/yyyy");
                Date currentDate = new Date();
                String currentTime = sdf.format(currentDate);
                lblThoiGian.setText(currentTime);
            }
        });
        timer.start();
        String tenGV = AppData.getQuanLy().getUsername();
        lblUser.setText("Xin chào, " + tenGV);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblThoiGian = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        panCha = new javax.swing.JPanel();
        btnGiangVien = new javax.swing.JButton();
        btnSinhVien = new javax.swing.JButton();
        btnHocPhi = new javax.swing.JButton();
        btnLop = new javax.swing.JButton();
        btnKhoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnMon = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuSuaThongTin = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("HỆ THỐNG QUẢN LÝ SINH VIÊN VÀ GIẢNG VIÊN");

        lblThoiGian.setBackground(new java.awt.Color(102, 255, 51));
        lblThoiGian.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblThoiGian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/icon/clock.png"))); // NOI18N

        lblUser.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 0, 0));
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/icon/user.png"))); // NOI18N
        lblUser.setText("Xin chào, user");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser)
                    .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(173, 173, 173))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnGiangVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/banner/QLGiangVien.png"))); // NOI18N
        btnGiangVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiangVienActionPerformed(evt);
            }
        });

        btnSinhVien.setBackground(new java.awt.Color(51, 255, 51));
        btnSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/banner/QLSinhVien.png"))); // NOI18N
        btnSinhVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinhVienActionPerformed(evt);
            }
        });

        btnHocPhi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/banner/QLHocPhi.png"))); // NOI18N
        btnHocPhi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHocPhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHocPhiActionPerformed(evt);
            }
        });

        btnLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/banner/QLLopHoc.png"))); // NOI18N
        btnLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLopActionPerformed(evt);
            }
        });

        btnKhoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/banner/QLKhoa.png"))); // NOI18N
        btnKhoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/icon/exit.png"))); // NOI18N
        btnThoat.setText("Thoát");

        btnMon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/public/banner/QLMon.png"))); // NOI18N
        btnMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panChaLayout = new javax.swing.GroupLayout(panCha);
        panCha.setLayout(panChaLayout);
        panChaLayout.setHorizontalGroup(
            panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panChaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panChaLayout.createSequentialGroup()
                        .addComponent(btnLop, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMon, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panChaLayout.createSequentialGroup()
                        .addComponent(btnGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panChaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );
        panChaLayout.setVerticalGroup(
            panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panChaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panChaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLop, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnMon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addGap(9, 9, 9))
        );

        jMenu1.setText("Thông tin quản lý");

        mnuSuaThongTin.setText("Sửa thông tin ");
        mnuSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSuaThongTinActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSuaThongTin);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Đăng xuất");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panCha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panCha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinhVienActionPerformed

        QuanLySinhVien sv = new QuanLySinhVien();
        sv.setLocationRelativeTo(null);
        sv.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        sv.show();


    }//GEN-LAST:event_btnSinhVienActionPerformed

    private void mnuSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSuaThongTinActionPerformed
        ThongTinCaNhanGV GV = new ThongTinCaNhanGV();
        GV.setVisible(true);

    }//GEN-LAST:event_mnuSuaThongTinActionPerformed

    private void btnGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiangVienActionPerformed
        QLGiangVien gv = new QLGiangVien();
        gv.setLocationRelativeTo(null);
        gv.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        gv.setVisible(true);
    }//GEN-LAST:event_btnGiangVienActionPerformed

    private void btnKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaActionPerformed
        QLKhoa khoa = new QLKhoa();
        khoa.setLocationRelativeTo(null);
        khoa.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        khoa.show();
    }//GEN-LAST:event_btnKhoaActionPerformed

    private void btnHocPhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHocPhiActionPerformed
        QLHocPhi hp = new QLHocPhi();
        hp.setLocationRelativeTo(null);
        hp.show();
    }//GEN-LAST:event_btnHocPhiActionPerformed

    private void btnLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLopActionPerformed
        QLLopHoc lop = new QLLopHoc();
        lop.setLocationRelativeTo(null);
        lop.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        lop.show();
    }//GEN-LAST:event_btnLopActionPerformed

    private void btnMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonActionPerformed
        QLMon mon = new QLMon();
        mon.setLocationRelativeTo(null);
        mon.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        mon.show();
    }//GEN-LAST:event_btnMonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChuQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrangChuQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiangVien;
    private javax.swing.JButton btnHocPhi;
    private javax.swing.JButton btnKhoa;
    private javax.swing.JButton btnLop;
    private javax.swing.JButton btnMon;
    private javax.swing.JButton btnSinhVien;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenuItem mnuSuaThongTin;
    private javax.swing.JPanel panCha;
    // End of variables declaration//GEN-END:variables
}
